name: tekartik_serial_wss_sim
description: Serial Wss simulation
version: 0.1.0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  web_socket_channel: any
  shelf_web_socket: any
  tekartik_serial_wss_client:
    git: git://github.com/tekartik/serial_wss_client.dart
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart
    version: '>=0.4.8'
dev_dependencies:
  test: ^0.12.0
  tekartik_test_menu:
    git: git://github.com/tekartik/test_menu.dart
dependency_overrides:
#  tekartik_serial_wss_client:
#    path: ../serial_wss_client.dart

executables:
  serial_wss_sim: