name: tekartik_serial_wss_sim
description: Serial Wss simulation
version: 0.2.2
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  web_socket_channel: any
  shelf_web_socket: any
  tekartik_serial_wss_client:
    git:
      url: git://github.com/tekartik/serial_wss_client.dart
      ref: dart1
    version: '>=0.4.0'
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart1
    version: '>=0.4.8'
dev_dependencies:
  test: ^0.12.0
  tekartik_test_menu:
    git:
      url: git://github.com/tekartik/test_menu.dart
      ref: dart1

dependency_overrides:
#  tekartik_serial_wss_client:
#    path: ../serial_wss_client.dart

executables:
  serial_wss_sim: