name: serial_wss_sim
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  web_socket_channel: any
  shelf_web_socket: any
  tekartik_serial_wss_client:
    git: git://github.com/tekartik/serial_wss_client.dart
dev_dependencies:
  test: ^0.12.0
  tekartik_test_menu:
    git: git://github.com/tekartik/test_menu.dart
