name: tekartik_serial_wss_sim
description: Serial Wss simulation
version: 0.3.3
publish_to: none
#homepage: https://www.example.com
author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  web_socket_channel: any
  shelf_web_socket: any
  tekartik_serial_wss_client:
    git:
      url: git://github.com/tekartik/serial_wss_client.dart
      ref: dart2
    version: '>=0.8.0'
  tekartik_web_socket_io:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: web_socket_io
      ref: dart2
    version: '>=0.1.0'
dev_dependencies:
  test: '>=1.0.0'
  tekartik_test_menu_io:
    git:
      url: git://github.com/tekartik/test_menu.dart
      ref: dart2
      path: test_menu_io
  dev_test: '>=0.13.2-dev.3'
dependency_overrides:
#  tekartik_serial_wss_client:
#    path: ../serial_wss_client.dart

executables:
  serial_wss_sim: